# Generated by Django 2.0.6 on 2019-11-06 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackpackModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonsterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('pictureURL', models.CharField(default='https://wingslax.com/wp-content/uploads/2017/12/no-image-available.png', max_length=200)),
                ('health', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('pictureURL', models.CharField(default='https://wingslax.com/wp-content/uploads/2017/12/no-image-available.png', max_length=200)),
                ('health', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('password', models.CharField(default='', max_length=200)),
                ('pictureURL', models.CharField(default='https://wingslax.com/wp-content/uploads/2017/12/no-image-available.png', max_length=200)),
                ('health', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='backpackmodel',
            name='foreignKeyShopItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raidmmo_serverapp.ShopItems'),
        ),
        migrations.AddField(
            model_name='backpackmodel',
            name='foreignKeyUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raidmmo_serverapp.User'),
        ),
    ]
