# Generated by Django 2.0.6 on 2019-11-06 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidmmo_serverapp', '0002_auto_20191106_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentRaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentMonsterForeignKey', models.IntegerField(default=1)),
            ],
        ),
    ]
