# Generated by Django 2.0.6 on 2019-11-07 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raidmmo_serverapp', '0003_currentraid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentRaid',
        ),
        migrations.AlterField(
            model_name='backpackmodel',
            name='foreignKeyShopItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backpack', to='raidmmo_serverapp.ShopItems'),
        ),
        migrations.AlterField(
            model_name='backpackmodel',
            name='foreignKeyUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='backpack', to='raidmmo_serverapp.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
