# Generated by Django 2.0.6 on 2019-11-07 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raidmmo_serverapp', '0005_auto_20191107_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitems',
            name='defense',
        ),
        migrations.RemoveField(
            model_name='user',
            name='defense',
        ),
    ]
