# Generated by Django 2.0.6 on 2019-11-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raidmmo_serverapp', '0006_auto_20191107_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictureURL',
            field=models.CharField(default='https://wingslax.com/wp-content/uploads/2017/12/no-image-available.png', max_length=1000),
        ),
    ]
